-- CreateTable
CREATE TABLE "Calls" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "OI" TEXT NOT NULL,
    "CHNG_IN_OI" TEXT NOT NULL,
    "VOLUME" TEXT NOT NULL,
    "IV" TEXT NOT NULL,
    "LTP" TEXT NOT NULL,
    "CHNG" TEXT NOT NULL,
    "BID_QTY" TEXT NOT NULL,
    "BID_PRICE" TEXT NOT NULL,
    "ASK_PRICE" TEXT NOT NULL,
    "ASK_QTY" TEXT NOT NULL,
    "STRIKE_PRICE" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "Puts" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "BID_QTY" TEXT NOT NULL,
    "BID_PRICE" TEXT NOT NULL,
    "ASK_PRICE" TEXT NOT NULL,
    "ASK_QTY" TEXT NOT NULL,
    "CHNG" TEXT NOT NULL,
    "LTP" TEXT NOT NULL,
    "IV" TEXT NOT NULL,
    "VOLUME" TEXT NOT NULL,
    "CHNG_IN_OI" TEXT NOT NULL,
    "OI" TEXT NOT NULL,
    "STRIKE_PRICE" TEXT NOT NULL
);
